In [10]:
import numpy as np

data = np.load("raw/MixedWM38.npz")
data

In [11]:
raw = data["arr_0"]
label = data["arr_1"]

In [5]:
np.unique(raw[0])

array([0, 1, 2], dtype=int32)

In [6]:
raw.shape

(38015, 52, 52)

In [10]:
raw

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
label.shape

(38015, 8)

In [9]:
len(np.unique(label, axis=0))

38

In [12]:
unique_labels = np.unique(label, axis=0)
label_to_int = {tuple(lbl): idx for idx, lbl in enumerate(unique_labels)}
# Convert labels to integers
int_labels = np.array([label_to_int[tuple(lbl)] for lbl in label])

In [17]:
label_to_int

{(0, 0, 0, 0, 0, 0, 0, 0): 0,
 (0, 0, 0, 0, 0, 0, 0, 1): 1,
 (0, 0, 0, 0, 0, 0, 1, 0): 2,
 (0, 0, 0, 0, 0, 1, 0, 0): 3,
 (0, 0, 0, 0, 1, 0, 0, 0): 4,
 (0, 0, 0, 0, 1, 0, 1, 0): 5,
 (0, 0, 0, 1, 0, 0, 0, 0): 6,
 (0, 0, 0, 1, 0, 0, 1, 0): 7,
 (0, 0, 0, 1, 1, 0, 0, 0): 8,
 (0, 0, 0, 1, 1, 0, 1, 0): 9,
 (0, 0, 1, 0, 0, 0, 0, 0): 10,
 (0, 0, 1, 0, 0, 0, 1, 0): 11,
 (0, 0, 1, 0, 1, 0, 0, 0): 12,
 (0, 0, 1, 0, 1, 0, 1, 0): 13,
 (0, 1, 0, 0, 0, 0, 0, 0): 14,
 (0, 1, 0, 0, 0, 0, 1, 0): 15,
 (0, 1, 0, 0, 1, 0, 0, 0): 16,
 (0, 1, 0, 0, 1, 0, 1, 0): 17,
 (0, 1, 0, 1, 0, 0, 0, 0): 18,
 (0, 1, 0, 1, 0, 0, 1, 0): 19,
 (0, 1, 0, 1, 1, 0, 0, 0): 20,
 (0, 1, 0, 1, 1, 0, 1, 0): 21,
 (0, 1, 1, 0, 0, 0, 0, 0): 22,
 (0, 1, 1, 0, 0, 0, 1, 0): 23,
 (0, 1, 1, 0, 1, 0, 0, 0): 24,
 (0, 1, 1, 0, 1, 0, 1, 0): 25,
 (1, 0, 0, 0, 0, 0, 0, 0): 26,
 (1, 0, 0, 0, 0, 0, 1, 0): 27,
 (1, 0, 0, 0, 1, 0, 0, 0): 28,
 (1, 0, 0, 0, 1, 0, 1, 0): 29,
 (1, 0, 0, 1, 0, 0, 0, 0): 30,
 (1, 0, 0, 1, 0, 0, 1, 0): 31,
 (1, 0, 0, 1, 1, 0

In [19]:
np.savez("data/Wafer/TransformedWaterMapData.npz", raw_data=raw, int_labels=int_labels)

# Preprocess


In [1]:
import numpy as np

data_path = "data/Wafer/TransformedWaterMapData.npz"
data = np.load(data_path)

images = data["raw_data"]
labels = data["int_labels"]

In [2]:
# Split the data into train, validation, and test sets
total_samples = images.shape[0]
train_size = int(0.7 * total_samples)  # 70% for training
val_size = int(0.15 * total_samples)  # 15% for validation
test_size = total_samples - train_size - val_size  # 15% for testing

train_images, train_labels = images[:train_size], labels[:train_size]
val_images, val_labels = (
    images[train_size : train_size + val_size],
    labels[train_size : train_size + val_size],
)
test_images, test_labels = (
    images[train_size + val_size :],
    labels[train_size + val_size :],
)

In [9]:
import os

train_images = train_images[:, np.newaxis, :, :]
val_images = val_images[:, np.newaxis, :, :]
test_images = test_images[:, np.newaxis, :, :]


# Function to save data
def save_data(images, labels, filename):
    np.savez(filename, images=images, labels=labels)


# Ensure the directory for saving the splits exists
save_dir = "data/Wafer/splits"
os.makedirs(save_dir, exist_ok=True)

# Save the splits
save_data(train_images, train_labels, os.path.join(save_dir, "train_data.npz"))
save_data(val_images, val_labels, os.path.join(save_dir, "val_data.npz"))
save_data(test_images, test_labels, os.path.join(save_dir, "test_data.npz"))

In [10]:
train_images.shape

(26610, 1, 52, 52)

# New splitting


In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
import os

# Load the data
data_path = "data/Wafer/TransformedWaterMapData.npz"
data = np.load(data_path)
images = data["raw_data"]
labels = data["int_labels"]

# Expand dimensions to match required shape
images = images[:, np.newaxis, :, :]

# Stratified split into train and temp (validation + test) sets
train_images, temp_images, train_labels, temp_labels = train_test_split(
    images, labels, test_size=0.3, stratify=labels, random_state=42
)

# Further stratified split temp set into validation and test sets
val_images, test_images, val_labels, test_labels = train_test_split(
    temp_images, temp_labels, test_size=0.5, stratify=temp_labels, random_state=42
)


# Function to save data
def save_data(images, labels, filename):
    np.savez(filename, images=images, labels=labels)


# Ensure the directory for saving the splits exists
save_dir = "data/Wafer/splits"
os.makedirs(save_dir, exist_ok=True)

# Save the splits
save_data(train_images, train_labels, os.path.join(save_dir, "train_data.npz"))
save_data(val_images, val_labels, os.path.join(save_dir, "val_data.npz"))
save_data(test_images, test_labels, os.path.join(save_dir, "test_data.npz"))

print("Data has been split and saved successfully.")

Data has been split and saved successfully.


In [8]:
np.unique(val_labels)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37])

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split
import os

# Load the data
data_path = "data/Wafer/TransformedWaterMapData.npz"
data = np.load(data_path)
images = data["raw_data"]
labels = data["int_labels"]

# Expand dimensions to match required shape
images = images[:, np.newaxis, :, :]

# Stratified split into train and test sets
train_images, test_images, train_labels, test_labels = train_test_split(
    images, labels, test_size=0.3, stratify=labels, random_state=42
)


# Check correspondence
def check_correspondence(images, labels):
    for i in range(len(labels)):
        if images[i] is None or labels[i] is None:
            return False
    return True


# Function to save data
def save_data(images, labels, filename):
    np.savez(filename, images=images, labels=labels)


# Ensure the directory for saving the splits exists
save_dir = "/hpc2hdd/home/mgong081/Projects/DivideMix-prestopping/data/Wafer/splits"
os.makedirs(save_dir, exist_ok=True)

# Save the splits if they correspond correctly
if check_correspondence(train_images, train_labels):
    save_data(train_images, train_labels, os.path.join(save_dir, "train_data.npz"))
else:
    print("Error: Train images and labels do not correspond correctly.")

if check_correspondence(test_images, test_labels):
    save_data(test_images, test_labels, os.path.join(save_dir, "test_data.npz"))
else:
    print("Error: Test images and labels do not correspond correctly.")

print(
    "Data has been split and saved successfully if there were no correspondence errors."
)

Data has been split and saved successfully if there were no correspondence errors.


In [22]:
(len(train_images), len(test_images))

(26610, 11405)

# Tain Val and Test


In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import os

# Load the data
data_path = "Wafer/TransformedWaterMapData.npz"
data = np.load(data_path)
images = data["raw_data"]
labels = data["int_labels"]

# Expand dimensions to match required shape
images = images[:, np.newaxis, :, :]

# Stratified split into train (70%) and temp (30%) sets
train_images, temp_images, train_labels, temp_labels = train_test_split(
    images, labels, test_size=0.3, stratify=labels, random_state=42
)

# Further stratified split temp set into validation (15%) and test (15%) sets
val_images, test_images, val_labels, test_labels = train_test_split(
    temp_images, temp_labels, test_size=0.5, stratify=temp_labels, random_state=42
)

In [2]:
indices = [
    2691,
    726,
    3929,
    23276,
    18097,
    17835,
    4101,
    17254,
    7898,
    23913,
    20606,
    1252,
    20693,
    1898,
    8628,
    9686,
    10579,
    25687,
    14867,
    11631,
    7085,
    24716,
    18525,
    9548,
    15876,
    23865,
    4972,
    20819,
    1629,
    14436,
    22147,
    3643,
    5167,
    17802,
    19578,
    6824,
    17860,
    20420,
    96,
    18677,
    6721,
    6013,
    1172,
    2407,
    17117,
    17738,
    2801,
    11546,
    679,
    10496,
    25864,
    10026,
    1147,
    25563,
    17579,
    26441,
    4422,
    24154,
    940,
    18474,
    21513,
    6869,
    8373,
    22284,
]

train_labels[indices]

array([14, 36, 24, 31, 28, 11, 30, 22,  7, 35, 19, 15, 18,  6, 13, 34,  0,
       23, 17, 35, 11, 27, 24, 29, 37, 29, 18, 30, 22, 25, 14,  7, 21,  4,
       35, 33, 12, 30, 11, 29,  6, 12, 35, 13, 31, 12,  8,  5, 34, 34, 35,
       35, 29, 28,  9, 17, 26, 16,  0, 17,  2, 21, 28, 18])

In [3]:
train_labels[726]

36

In [8]:
from collections import Counter

Counter(train_labels), Counter(val_labels), Counter(test_labels)

(Counter({31: 700,
          7: 700,
          24: 700,
          27: 700,
          15: 700,
          30: 700,
          8: 700,
          19: 700,
          32: 700,
          26: 700,
          20: 700,
          23: 700,
          17: 700,
          33: 700,
          18: 700,
          37: 700,
          10: 700,
          2: 700,
          22: 700,
          0: 700,
          9: 700,
          29: 700,
          4: 700,
          6: 700,
          34: 700,
          36: 700,
          16: 700,
          14: 700,
          28: 700,
          5: 700,
          35: 1400,
          13: 700,
          21: 700,
          11: 700,
          12: 700,
          1: 606,
          25: 700,
          3: 104}),
 Counter({8: 150,
          35: 300,
          16: 150,
          20: 150,
          21: 150,
          12: 150,
          9: 150,
          15: 150,
          22: 150,
          33: 150,
          24: 150,
          7: 150,
          14: 150,
          0: 150,
          18: 150,
    

In [ ]:
# Check correspondence
def check_correspondence(images, labels):
    for i in range(len(labels)):
        if images[i] is None or labels[i] is None:
            return False
    return True


# Function to save data
def save_data(images, labels, filename):
    np.savez(filename, images=images, labels=labels)


# Ensure the directory for saving the splits exists
save_dir = "/hpc2hdd/home/mgong081/Projects/DivideMix-prestopping/data/Wafer/3splits"
os.makedirs(save_dir, exist_ok=True)

# Save the splits if they correspond correctly
if check_correspondence(train_images, train_labels):
    save_data(train_images, train_labels, os.path.join(save_dir, "train_data.npz"))
else:
    print("Error: Train images and labels do not correspond correctly.")

if check_correspondence(val_images, val_labels):
    save_data(val_images, val_labels, os.path.join(save_dir, "val_data.npz"))
else:
    print("Error: Validation images and labels do not correspond correctly.")

if check_correspondence(test_images, test_labels):
    save_data(test_images, test_labels, os.path.join(save_dir, "test_data.npz"))
else:
    print("Error: Test images and labels do not correspond correctly.")

print(
    "Data has been split and saved successfully if there were no correspondence errors."
)

In [11]:
train_images.shape

(26610, 1, 52, 52)